#spawn Categories(MONSTER, CREATURE, ... defaults..., custom pools from other mods
spawnCategories = ["MONSTER,40", "CREATURE,6", "AMBIENT,10", "AXOLOTLS,3", "UNDERGROUND_WATER_CREATURE,3", "WATER_CREATURE,3", "WATER_AMBIENT,12"]

